workspace:
  base: /drone
  path: src

pipeline:
image: node:latest
script:
 - npm install
 - ls  
 - pwd
 - mkdir -p  /home/ubuntu/ramalingam
 - cp -rv node_modules /home/ubuntu/deleteui/deleteui/  

